### ISSUE TITLE
Please consider joining stackage

### ISSUE THREAD

**Issue by nomeata** [cheecheeo/haskell-cgi#19]
Hi,

it would make life easier for distribution packagers if your package were inluded in stackage. See http://www.stackage.org/authors for instructions to do so.

Thanks,
Joachim

**Comment by cheecheeo** [comment]
You can track progress here: https://github.com/fpco/stackage/pull/522

**Comment by nomeata** [comment]
Thanks, great!

**Comment by cheecheeo** [comment]
merged in stackage
