### ISSUE TITLE
Please release 3001.3.0.3 to Hackage

### ISSUE THREAD

**Issue by peti** [cheecheeo/haskell-cgi#40]
`master` at d6d86abb61fa95fd168b57be8b4d3eb68c84f59b is in good shape and should IMHO be released to Hackage to fix the build with GHC 8.6.2.  If you can give me (http://hackage.haskell.org/user/PeterSimons) appropriate privileges on Hackage, then I'd be happy to do the upload myself, too.

[![travis build status](https://img.shields.io/travis/cheecheeo/haskell-cgi/master.svg?label=travis+build)](https://travis-ci.org/cheecheeo/haskell-cgi)

**Comment by cheecheeo** [comment]
![image](https://user-images.githubusercontent.com/175882/48494550-fc850000-e7e2-11e8-9092-7f3e23d1f838.png)

please give it a try

**Comment by peti** [comment]
Woohoo: https://hackage.haskell.org/package/cgi-3001.3.0.3
